Cb 4 team
Codubee/ExploreCitiesMW4-6 pull request #4
Opened 2020-11-18 21:33 UTC by ImaadAziz

* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]
CB-4-Team

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
Adds the team component.

* **What is the current behavior?What does the code do before you made the new changes?** 
There was no existing team component.

* **What is the new behavior?**
Adds the new component.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
No it should not.

* **Other information**:

2020-11-23 02:27 UTC, Codubee requested changes
Hi Imaad, great work! Left some comments to discuss some things.

2020-11-23 02:27 UTC, Codubee commented on frontend/src/App.js
> +import LandingPage from './components/LandingPage/LandingPage.js'
The .js is implied so it does not have to be added to the import.

2020-11-23 02:27 UTC, Codubee commented on frontend/src/components/LandingPage/Team/Team.js
> +const TeamCard = (props) => {
I would prefer to make the files have one component only. What do you think about creating another file containing the team card and then importing it into here.

2020-12-03 03:02 UTC, jadendick requested changes

2020-12-03 03:02 UTC, jadendick commented on frontend/src/components/LandingPage/Team/Team.js
> +const TeamCard = (props) => {
I think you need to delete this since you defined TeamCard in TeamCard.js

2020-12-09 06:34 UTC, Codubee approved these changes
LGTM!

2020-12-09 06:36 UTC, merged